# Generated by Django 5.2.8 on 2025-11-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='insights',
            field=models.TextField(blank=True, default=''),
        ),
    ]
